version: "3"

services:
  nodebb:
    image: nodebb/nodebb:latest
    container_name: nodebb
    ports:
      - "4567:4567"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodebb-data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - ./redis-data:/data
